docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Figlets: figlet.md
    - Tables: table.md
site_name: laminas-text
site_description: Laminas\Text
repo_url: 'https://github.com/laminas/laminas-text'
