docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Figlets: figlet.md
    - Tables: table.md
site_name: zend-text
site_description: "Create FIGlets and text-based tables"
repo_url: 'https://github.com/zendframework/zend-text'
