docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Figlets: figlet.md
    - Tables: table.md
site_name: zend-text
site_description: Zend\Text
repo_url: 'https://github.com/zendframework/zend-text'
copyright: 'Copyright (c) 2005-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
